import Constants from 'expo-constants';
import { useState } from 'react';
import { Alert, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';

import { AccentColors } from '@/constants/theme';
import { AppScreen } from '@/components/ui/app-screen';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { SectionHeader } from '@/components/ui/section-header';
import { useAppTheme } from '@/hooks/use-app-theme';
import { useFocusStore } from '@/stores/use-focus-store';
import { useSettingsStore } from '@/stores/use-settings-store';
import { useTasksStore } from '@/stores/use-tasks-store';

export default function SettingsScreen() {
  const { colors, accent } = useAppTheme();
  const settings = useSettingsStore((state) => state.settings);
  const updateSettings = useSettingsStore((state) => state.updateSettings);
  const resetSettings = useSettingsStore((state) => state.resetSettings);
  const clearSessions = useFocusStore((state) => state.clearSessions);
  const clearTasks = useTasksStore((state) => state.clearTasks);
  const sessionsCount = useFocusStore((state) => state.sessions.length);
  const [editor, setEditor] = useState<'focus' | 'goal' | null>(null);
  const [editorValue, setEditorValue] = useState('');

  function openEditor(type: 'focus' | 'goal') { setEditor(type); setEditorValue(String(type === 'focus' ? settings.defaultFocusMinutes : settings.dailyGoalMinutes)); }
  async function saveEditor() { const value = Number(editorValue); if (!Number.isFinite(value)) return; if (editor === 'focus' && value >= 1 && value <= 180) await updateSettings({ defaultFocusMinutes: Math.round(value) }); if (editor === 'goal' && value >= 1 && value <= 1440) await updateSettings({ dailyGoalMinutes: Math.round(value) }); setEditor(null); }
  function deleteAll() { Alert.alert('Delete all focus data?', 'This permanently removes your tasks, sessions, and streak history stored on this device.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete Everything', style: 'destructive', onPress: () => { void Promise.all([clearSessions(), clearTasks(), resetSettings()]); } }]); }

  return <AppScreen><View style={styles.header}><Text style={[styles.eyebrow, { color: accent }]}>PERSONALIZE</Text><Text style={[styles.title, { color: colors.text }]}>Settings</Text><Text style={[styles.subtle, { color: colors.textSecondary }]}>Keep FocusFlow tuned to your rhythm.</Text></View>
    <SectionHeader title="Focus" /><Card><SettingRow label="Default focus duration" value={`${settings.defaultFocusMinutes} min`} colors={colors} onPress={() => openEditor('focus')} /><PresetChips values={[15, 25, 45, 60]} selected={settings.defaultFocusMinutes} onSelect={(value) => void updateSettings({ defaultFocusMinutes: value })} colors={colors} accent={accent} /><SettingRow label="Daily focus goal" value={`${settings.dailyGoalMinutes} min`} colors={colors} onPress={() => openEditor('goal')} /><PresetChips values={[30, 60, 90, 120, 180, 240]} selected={settings.dailyGoalMinutes} onSelect={(value) => void updateSettings({ dailyGoalMinutes: value })} colors={colors} accent={accent} /></Card>
    <SectionHeader title="Timer" /><Card><ToggleRow label="Completion sound" value={settings.soundEnabled} colors={colors} onPress={() => void updateSettings({ soundEnabled: !settings.soundEnabled })} /><ToggleRow label="Haptic feedback" value={settings.hapticsEnabled} colors={colors} onPress={() => void updateSettings({ hapticsEnabled: !settings.hapticsEnabled })} /><ToggleRow label="Notifications" value={settings.notificationsEnabled} colors={colors} onPress={() => void updateSettings({ notificationsEnabled: !settings.notificationsEnabled })} /></Card>
    <SectionHeader title="Appearance" /><Card><Text style={[styles.optionLabel, { color: colors.textSecondary }]}>Theme</Text><View style={styles.segmented}>{(['system', 'light', 'dark'] as const).map((theme) => <Pressable key={theme} accessibilityRole="button" onPress={() => void updateSettings({ theme })} style={[styles.segment, { backgroundColor: settings.theme === theme ? accent : colors.backgroundSelected }]}><Text style={{ color: settings.theme === theme ? '#fff' : colors.text, fontWeight: '700', textTransform: 'capitalize' }}>{theme}</Text></Pressable>)}</View><Text style={[styles.optionLabel, { color: colors.textSecondary, marginTop: 20 }]}>Accent color</Text><View style={styles.colors}>{AccentColors.map((color) => <Pressable key={color} accessibilityRole="button" accessibilityLabel={`Use accent ${color}`} onPress={() => void updateSettings({ accentColor: color })} style={[styles.colorSwatch, { backgroundColor: color, borderColor: settings.accentColor === color ? colors.text : 'transparent' }]}><Text style={styles.colorCheck}>{settings.accentColor === color ? '✓' : ''}</Text></Pressable>)}</View></Card>
    <SectionHeader title="Data" /><Card><Text style={[styles.dataCount, { color: colors.text }]}>{sessionsCount} session{sessionsCount === 1 ? '' : 's'} stored locally</Text><Text style={[styles.subtle, { color: colors.textSecondary }]}>Your data never leaves this device.</Text><Button onPress={deleteAll} variant="danger" style={styles.deleteButton}>Delete all focus data</Button></Card>
    <SectionHeader title="About" /><Card><Text style={[styles.aboutName, { color: colors.text }]}>FocusFlow</Text><Text style={[styles.subtle, { color: colors.textSecondary }]}>Version {Constants.expoConfig?.version ?? '1.0.0'} · Offline by design</Text><Text style={[styles.privacy, { color: colors.textSecondary }]}>Your focus data stays on your device. FocusFlow does not require an account and does not upload your productivity data.</Text></Card>
    <Modal visible={editor !== null} transparent animationType="slide" onRequestClose={() => setEditor(null)}><View style={styles.backdrop}><View style={[styles.modal, { backgroundColor: colors.backgroundElement }]}><Text style={[styles.modalTitle, { color: colors.text }]}>Set {editor === 'focus' ? 'default focus duration' : 'daily focus goal'}</Text><TextInput autoFocus keyboardType="number-pad" value={editorValue} onChangeText={setEditorValue} style={[styles.input, { color: colors.text, borderColor: colors.border, backgroundColor: colors.background }]} /><Text style={[styles.hint, { color: colors.textSecondary }]}>{editor === 'focus' ? 'Choose between 1 and 180 minutes.' : 'Choose between 1 and 1,440 minutes.'}</Text><View style={styles.modalActions}><Button onPress={() => setEditor(null)} variant="ghost" style={styles.modalButton}>Cancel</Button><Button onPress={() => void saveEditor()} style={styles.modalButton}>Save</Button></View></View></View></Modal>
  </AppScreen>;
}

function SettingRow({ label, value, colors, onPress }: { label: string; value: string; colors: { text: string; textSecondary: string; border: string }; onPress: () => void }) { return <Pressable accessibilityRole="button" onPress={onPress} style={[styles.row, { borderBottomColor: colors.border }]}><Text style={[styles.rowLabel, { color: colors.text }]}>{label}</Text><Text style={[styles.rowValue, { color: colors.textSecondary }]}>{value}  ›</Text></Pressable>; }
function ToggleRow({ label, value, colors, onPress }: { label: string; value: boolean; colors: { text: string; textSecondary: string; backgroundSelected: string }; onPress: () => void }) { return <Pressable accessibilityRole="switch" accessibilityState={{ checked: value }} onPress={onPress} style={styles.row}><Text style={[styles.rowLabel, { color: colors.text }]}>{label}</Text><View style={[styles.toggle, { backgroundColor: value ? '#45A779' : colors.backgroundSelected }]}><View style={[styles.toggleKnob, { alignSelf: value ? 'flex-end' : 'flex-start' }]} /></View></Pressable>; }
function PresetChips({ values, selected, onSelect, colors, accent }: { values: number[]; selected: number; onSelect: (value: number) => void; colors: { text: string; backgroundSelected: string }; accent: string }) { return <View style={styles.presetWrap}>{values.map((value) => <Pressable key={value} accessibilityRole="button" onPress={() => onSelect(value)} style={[styles.preset, { backgroundColor: selected === value ? accent : colors.backgroundSelected }]}><Text style={{ color: selected === value ? '#fff' : colors.text, fontSize: 12, fontWeight: '700' }}>{value}m</Text></Pressable>)}</View>; }

const styles = StyleSheet.create({ header: { marginBottom: 30 }, eyebrow: { fontSize: 12, fontWeight: '800', letterSpacing: 1.8 }, title: { fontSize: 34, fontWeight: '800', letterSpacing: -1, marginTop: 7 }, subtle: { fontSize: 14, lineHeight: 20 }, row: { minHeight: 58, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: StyleSheet.hairlineWidth }, rowLabel: { fontSize: 15, fontWeight: '600' }, rowValue: { fontSize: 14 }, toggle: { width: 48, height: 28, borderRadius: 14, padding: 3, justifyContent: 'center' }, toggleKnob: { width: 22, height: 22, borderRadius: 11, backgroundColor: '#fff' }, optionLabel: { fontSize: 13, fontWeight: '700' }, segmented: { flexDirection: 'row', gap: 8, marginTop: 10 }, segment: { flex: 1, alignItems: 'center', paddingVertical: 11, borderRadius: 12 }, presetWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, paddingVertical: 10 }, preset: { borderRadius: 10, paddingHorizontal: 11, paddingVertical: 9 }, colors: { flexDirection: 'row', gap: 12, marginTop: 12 }, colorSwatch: { width: 34, height: 34, borderRadius: 17, borderWidth: 3, alignItems: 'center', justifyContent: 'center' }, colorCheck: { color: '#fff', fontWeight: '800' }, dataCount: { fontSize: 17, fontWeight: '800', marginBottom: 5 }, deleteButton: { marginTop: 18 }, aboutName: { fontSize: 20, fontWeight: '800', marginBottom: 5 }, privacy: { fontSize: 14, lineHeight: 21, marginTop: 18 }, backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.45)' }, modal: { padding: 24, borderTopLeftRadius: 28, borderTopRightRadius: 28 }, modalTitle: { fontSize: 22, fontWeight: '800', marginBottom: 18 }, input: { minHeight: 54, borderWidth: 1, borderRadius: 14, paddingHorizontal: 15, fontSize: 18 }, hint: { fontSize: 13, marginTop: 8 }, modalActions: { flexDirection: 'row', gap: 10, marginTop: 18 }, modalButton: { flex: 1 } });
